version: "3.9"

services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: my_StrapiDB
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_USER: strapi
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_DATABASE: my_StrapiDB
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi